### ISSUE TITLE
First boundary skipped

### ISSUE THREAD

**Issue by nicolas-cherel** [cybergeek94/multipart#15]
me again, about this change : 

https://github.com/cybergeek94/multipart/blob/master/src/server/mod.rs#L61

The first boundary that comes from hyper won't have the \r\n, since the multipart is the http content body, the two previous CRLF are part of the header. It's a real pain, since it removes a simple way to strip the extras CRLF around the boundary.

I'll try to figure out a sensible solution and submit a PR later

**Comment by cybergeek94** [comment]
Closed in #16, thanks!.
