### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by LukasKalbertodt** [cybergeek94/multipart#2]
Hi there,

it seems like this repo died a few months ago. Any plans to continue this project? Or are there any good alternatives?

**Comment by cybergeek94** [comment]
I haven't been working on it because I didn't think anyone was interested. I can update it to compile on latest Rust or accept your PR if you want to do it.

**Comment by LukasKalbertodt** [comment]
Yep I'm interested in this. Actually I cannot believe that no one needs this... I don't want to write a boundary-find-algorithm just to make some kind of simple HTTP-request. Don't other Rust developer need that? I'm really confused.

But yes, if you have some time to spare, it would be really nice to use this. :+1:

**Comment by cybergeek94** [comment]
All the web stuff in Rust is still so early on, it makes sense why no one needs to accept multipart requests yet. I have to leave in a few hours for a family function since today's a holiday in the US, but I'll see what I can do.

**Comment by LukasKalbertodt** [comment]
No hurry!

I am reading a bit through the code right now. One thought: It would be cool to make it independent of hyper. Should be possible by just taking io::Read and io::Write, shouldn't it? I think it would be nice to modernize this crate, instead of just make it compile.

Another thing: It looks to me like you don't actually check your boundary for the client. You just create a random string and hope for the best. 

What do you think? As I said: I could help with a few hours.

**Comment by cybergeek94** [comment]
Well it needs to read headers from the request to determine whether or not the it is a multipart request, and if so, the boundary. I guess I could make Hyper optional and create a trait to implement for Hyper's `Request` object:

```rust
pub trait MaybeMultipart {
    fn is_multipart(&self) -> bool;
    fn bounary(&self) -> &str;
}
```

I have some time to kill so I'll create a `revival` branch and start doing this work there.

**Comment by cybergeek94** [comment]
Wait, what.... all the source files are empty! I was in the middle of a rewrite and I guess I committed broken code. At least the hardest part to write, `BoundaryReader`, is still intact.

**Comment by LukasKalbertodt** [comment]
I looked through the code on the "crates" branch... I was wondering why clients.rs is empty on master, too ;)

**Comment by cybergeek94** [comment]
I reverted that commit, there should be code back on `master` now.

**Comment by LukasKalbertodt** [comment]
> What needs to be checked? The generated boundary string is alphanumeric, that's all it needs to be valid according to my research. Edit: it's not alphanumeric, just ASCII. I'll fix that.

The boundary musn't appear in one of the payloads. If one of the payloads (a file for example) contains the boundary the server can't parse the body. Or am I missing something?

And about hyper: This trait trick should work, but its not optimal IMO... Don't know if theres a way to make it work easily. Maybe this crate should concentrate on the body parsing alone and forget about headers completely. Or what do you think?

**Comment by LukasKalbertodt** [comment]
http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4

> Part boundaries should not occur in any of the data; how this is done lies outside the scope of this specification.

**Comment by cybergeek94** [comment]
> The boundary musn't appear in one of the payloads. If one of the payloads (a file for example) contains the boundary the server can't parse the body. Or am I missing something?

No, that's right. But it's unfeasible to check every file for the boundary sequence, especially if they're all very large. So we generate a relatively high-entropy random string and hope for the best.

**Comment by LukasKalbertodt** [comment]
Ok, already thought about the near 0 probability that a random boundary string appears in the payload. But still: It sounds wrong to me... 

Maybe thats why nobody uses this crate: Generating a random string is "fairly easy" :P 
One could at least add an optional method `check_boundary`...

**Comment by cybergeek94** [comment]
You can check what Firefox or Chrome does but I very much doubt they check their payloads for occurrences of the boundary string. The guys on `#rust-webdev` or `#servo` on the Mozilla IRC would know better than I do. If they say we should check the boundary string, then we'll check the boundary string. :)

**Comment by LukasKalbertodt** [comment]
I checked [`curl`](https://github.com/bagder/curl/blob/8f4791440a940cbc7bd5a911ae5344b117669dcc/lib/formdata.c#L1517) and yes, it's just random. And @sfackler told me in `#rust-webdev`: 

> I belive implementations just make a big random string and hope things work out, which they will with absurdly high probability

So yes, apparently no one checks the boundary. I really thought it should be checked in production. So I've learned something today ^_^

**Comment by cybergeek94** [comment]
All right, have a look at the `revival` branch. I'll be out for a couple hours but I'll be back to continue this later.

**Comment by LukasKalbertodt** [comment]
I have created a PR to fix the build script and tried to compile it with rust stable. Currently `mime_guess` uses unstable features, which should be fixed easily. But have you considered switching to [mime-types](https://github.com/conduit-rust/mime-types)? It looks like a more complete list. Although its not as easy to use... I'm not sure about that.

**Comment by cybergeek94** [comment]
`mime_guess` actually came a long time before`mime-types`. I just never bothered to advertise it to the community. `mime-types` doesn't interface directly with the `mime` crate and also builds a hashmap at runtime; I was able to achieve a zero-setup binary search by just having an ordered static slice. :smile:

**Comment by LukasKalbertodt** [comment]
Zero-setup, but possible more runtime cost for every query? I'm really not sure, which solution is better here. I just thought about using a `lazy_static` HashMap or something. But it's not really important right now ;)

**Comment by cybergeek94** [comment]
Tradeoffs, tradeoffs, tradeoffs. `mime-types` parses the whole list from JSON, so the setup cost is pretty large if you're only doing one or two lookups. It also uses more memory overall, because it and `mime_guess` both store the master list but `mime-types` also copies it to the heap at runtime. Very inefficient.

I also forgot to mention that I tried all that before, and realized this was the simpler solution.

**Comment by cybergeek94** [comment]
Well, one big change that I'm going to have to figure my way around is that readers no longer return `Err` when they are at EOF. They just return 0 bytes read and let the user assume that the reader has reached its end.
