### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by jyasskin** [cybergeek94/multipart#22]
Your README points to http://rust-ci.org/cybergeek94/multipart/doc/multipart/, which is a 404.

**Comment by jyasskin** [comment]
Your [Travis CI build](https://travis-ci.org/cybergeek94/multipart/jobs/72920580) says:

> upload failed: doc/FiraSans-Medium.woff to s3://rust-ci-artifacts/artifacts/cybergeek94-multipart-master/72920579/72920580/FiraSans-Medium.woff A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.

**Comment by cybergeek94** [comment]
Thanks for bringing this to my attention. Sorry for the delay, I had more pressing matters to take care of.

I updated the Rust-CI token but I'm getting a new error when it attempts the docs upload. [Travis CI Build log](https://travis-ci.org/cybergeek94/multipart/jobs/76511853)

It looks like an issue with the upload script generated by Rust-CI, perhaps it's trying to use an outdated `pip` package. If I load the URL manually it downloads just fine, so it might have just been a one-time problem.

**Comment by cybergeek94** [comment]
Documentation is now hosted on Github Pages.
