### ISSUE TITLE
First entry is being skipped

### ISSUE THREAD

**Issue by bltavares** [cybergeek94/multipart#26]
Hi there,

I was trying out multipart on a form with a single file field, but I was not being able to get the result back.

I've created an example project to reproduce the issue. On this project, there is 3 file fields that I submit on the request, but the first is getting skipped.
https://github.com/bltavares/multipart-skipping-field-bug-report

I was trying to pinpoint why it was happening, and the closer I got was that we were reaching this line.
https://github.com/cybergeek94/multipart/blob/master/src/server/mod.rs#L166

I'm not so sure why it is getting there, but I would be open to help with the fix if you could give me some guidance.

Cheers (:

**Comment by cybergeek94** [comment]
@bltavares I believe I have fixed this now. Could you please update your Cargo.toml to use `multipart="0.4.1-alpha"` and let me know if it works as expected?

**Comment by cybergeek94** [comment]
Actually just make that `multipart="0.4.1"`, there's a bug with prerelease version parsing in Cargo.

**Comment by bltavares** [comment]
@cybergeek94 thank you, It has been fixed on `0.4.1`.

Cheers!

**Comment by cybergeek94** [comment]
Good to hear! Thanks for the report.
