### ISSUE TITLE
[Easy/Mentored] Create Sample Projects

### ISSUE THREAD

**Issue by cybergeek94** [cybergeek94/multipart#29]
I started to work on sample projects for each of the features in this release, but I realized it would be a perfect opportunity to mentor some beginners to Rust webdev!

If you are interested in tackling any of these, let me know on this PR and we'll coordinate on the `#rust-webdev` channel of the Mozilla IRC or another communication channel of your choosing.

Each of the following items will be created as a new Cargo binary project `cargo new --bin [name]` under a new `samples/` directory in this repo. When done, they should be submitted via a PR. Each solution should have sufficient documentation in comments (not necessarily step-by-step, but perhaps a high-concept overview of each stage of request submission/reception).

- [x] `hyper_client`: use `multipart::client::Multipart` and `hyper::client::Request` to make a multipart request to `localhost:80` with a text field, a file field (as `myfile.txt` in the root of the sample project with a paragraph of [*lorem ipsum* text](http://www.lipsum.com/), and stream field (with a vector of random/arbitrary bytes as the source).

- [x] `hyper_reqbuilder`: use `multipart::client::lazy::Multipart` and `hyper::Client` to make the same request as above.

- [x] `hyper_server`: host a server with `hyper::Server` on `localhost:80` and use `multipart::server::Multipart` to intercept multipart requests and read out all fields (text and file/stream) to stdout.

- [x] `iron`: do the same as above, but with `iron::Request` instead of Hyper.

- [x] `iron_intercept`: create a `iron::Chain` coupling  the `multipart::server::iron::Intercept` before-middleware and a handler which extracts the `multipart::server::Entries` from the request and reads the fields to stdout.

- [x] `tiny_http` (completed by @White-Oak): do the same as `hyper_server` but with `tiny_http`.

- [x] `nickel`: do the same as `hyper_server` but with Nickel.

**Comment by HM0880** [comment]
I'm working on the `hyper_client` example now.  I'll submit a PR when it's done.

**Comment by cybergeek94** [comment]
@HM0880 Cheers! Feel free to take any of the others if you like, let me know if you need help.

**Comment by hatsunearu** [comment]
Is `hyper_server` taken? I am interested in picking it up starting this weekend.

**Comment by cybergeek94** [comment]
@hatsunearu not to my knowledge, feel free to take it up! I'll start tracking who's doing what in the issue.

**Comment by White-Oak** [comment]
Can i claim `tiny_http` one?

**Comment by cybergeek94** [comment]
@White-Oak Sure, go right ahead!

**Comment by cybergeek94** [comment]
@HM0880 @hatsunearu @White-Oak So you guys know, I don't normally get on IRC so if you need help or advice just ping me on this issue or send me an email or a PM on reddit.

**Comment by cybergeek94** [comment]
@HM0880 @hatsunearu A general note to keep in mind, based off @White-Oak's PR (#31):

`.unwrap()` should be avoided where it makes more sense to recover from errors than panic, especially for the server-side where you don't want a single malformed request to bring down the whole server process. 

This is still applicable to client applications which don't necessarily need to keep running after an error, as panics tend to pollute the console with information that don't mean much to end-users. Even without `RUST_BACKTRACE=1` you'll still get something like:

> thread '\<main\>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:688`). 

When the only relevant part of the message was "no such file or directory".

Where possible, it's better to print the error message and `continue` (if in a loop) or `return` (from `fn main`). You get a much nicer printout if you do something like:

```rust
// If the Ok(_) value doesn't mean anything:
if let Err(err) = <fallible operation here> {
    println!("Error processing request: {}", err);
   <continue or return>
}

// If you want the Ok(_) value:
match <fallible operation> {
    Ok(val) => use_val(val),
    Err(err) => {
        println!("Error doing the thing: {}", err);
        <continue or return>
    },
}
```

**Comment by cybergeek94** [comment]
Merged #31, thanks for the `tiny_http` sample @White-Oak! Good work.

**Comment by White-Oak** [comment]
If noone minds I'll take the `iron` as well.

**Comment by cybergeek94** [comment]
@White-Oak Go ahead! I'm sure if someone wanted it they'd have claimed it by now.

**Comment by White-Oak** [comment]
@cybergeek94 hey, the most recent version of `iron` is `0.3`, but you depend on `0.2` and there is something that breaks compatibility between these. Just wanted you to know.

**Comment by cybergeek94** [comment]
@White-Oak can you open an issue on that? I'll upgrade it in a bit, or you can have a go at it if you want.

**Comment by White-Oak** [comment]
@cybergeek94 I'll wait for you to upgrade it.

**Comment by cybergeek94** [comment]
Pinging @HM0880 @hatsunearu any progress on your ends? There's no hurry in finishing, you've just been inactive for a while and I'm wondering if you're still interested in doing this. If not, that's okay, I just have to know so I can make the tasks available for someone else.

**Comment by cybergeek94** [comment]
@White-Oak you're the only one that's committed code so far so at this point this really only concerns you. I'm considering giving the sample projects a public domain/copyfree license like [CC0](https://en.wikipedia.org/wiki/Creative_Commons_license#Zero_.2F_public_domain) or [WTFPL](https://en.wikipedia.org/wiki/WTFPL) to eliminate any hindrances in using them to bootstrap a project. What do you think?

**Comment by HM0880** [comment]
@cybergeek94 Yes, still interested. Work and life have been very busy lately. I hope to get to it soon. :)

**Comment by White-Oak** [comment]
@cybergeek94 I'm fine with public domain, but no WTFPL, please.
I have also looked into implementing 'hyper_reqbuilder' sample, so if you haven't started on it yet, I can make a PR.

**Comment by cybergeek94** [comment]
@White-Oak Please, go ahead. 

I can understand not wanting the WTFPL. I've also been looking at [the Unlicense](http://unlicense.org/), which is probably the best one though I don't think it's necessary to go as far as requiring contributors to explicitly waive their copyrights and/or digitally sign a release.

**Comment by hatsunearu** [comment]
I'm still interested. I'm also pretty busy with studies and life, and I hope to get it done in the coming weeks. I don't care about licenses, but Public Domain seems a bit more professional.

**Comment by cybergeek94** [comment]
New integration coming: Nickel!

It'll need a sample project like the others. Anyone interested?

**Comment by cybergeek94** [comment]
When #37 is merged, the *lorem ipsum* text file will be available under `samples/`.

**Comment by cybergeek94** [comment]
Pinging @HM0880 @White-Oak @hatsunearu 

You all still alive?

**Comment by hatsunearu** [comment]
Yeah, I just started work at NVIDIA and I have pretty much zero time to work on this unfortunately. I'm really sorry but I'll have to give up on it. If nobody does it after my next semester begins I might take a second shot at it.

Sorry about the mess.

On May 19, 2016 4:55 PM, Austin Bonander <notifications@github.com> wrote:

Pinging @HM0880<https://github.com/HM0880> @White-Oak<https://github.com/White-Oak> @hatsunearu<https://github.com/hatsunearu>

You all still alive?

**Comment by cybergeek94** [comment]
@hatsunearu Congratulations on the new job! Don't worry about the sample project, I'll get it done.

**Comment by HM0880** [comment]
Yes, still alive and still interested! Am in the process of changing jobs, but that should calm down in a few weeks. I'd still love to do this, but if someone else is interested and is more available, feel free to give it to them.

**Comment by puhrez** [comment]
Hey! I'm interesting in `hyper_server`, I'll get on it soon!

**Comment by iamsebastian** [comment]
Just do a reference to the nickel.rs example: #48

**Comment by cybergeek94** [comment]
All examples have been completed! Thanks all!
