### ISSUE TITLE
Iron dependency is outdated

### ISSUE THREAD

**Issue by White-Oak** [cybergeek94/multipart#33]
https://crates.io/crates/iron is on `0.3`, while `multipart` depends on `0.2`. They are probably at most compatible.

However, when I was trying to `Multipart::from_request` from Iron Request, `rustc` was terribly angered, complaining traits being not implemented. The issue was gone, when I specified `iron 0.2` as a dependency of my sample.

**Comment by cybergeek94** [comment]
It's probably as simple as bumping Iron to `0.3` for `multipart` itself. If you'd rather wait, I can take care of it in a few hours.

In the meantime, just create the sample against Iron 0.2
