### ISSUE TITLE
Mime dependency is outdated

### ISSUE THREAD

**Issue by White-Oak** [cybergeek94/multipart#35]
0.1 versus 0.2

**Comment by White-Oak** [comment]
Is it possible to reexport types, so one wouldn't need to state a matching version of a dependency in Cargo.toml, but use what library is using?

**Comment by cybergeek94** [comment]
If Cargo was smart enough to match dependencies within a range of versions, this wouldn't really be an issue. I guess it's more computationally complex than it seems: https://github.com/rust-lang/cargo/issues/2064

Updating to `mime 0.2` is generally trivial, though. I'll get to it in a bit.

**Comment by cybergeek94** [comment]
I actually have already done this update on the `0.6` branch, so I'll roll in the update to Iron and roll it out.
