### ISSUE TITLE
Hyper Clinet type mismatch

### ISSUE THREAD

**Issue by paomian** [cybergeek94/multipart#46]
when I call `client_request` in mp which type is `multipart::client::lazy::Multipart` and i got this error? I can't understand  `&hyper::Client` is not same with `&hyper::client::Client`?
```
src/main.rs:32:23: 32:52 error: mismatched types [E0308]
src/main.rs:32     mp.client_request(&hyper::client::Client::new(),"http://localhost:1234");
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.rs:32:23: 32:52 help: run `rustc --explain E0308` to see a detailed explanation
src/main.rs:32:23: 32:52 note: expected type `&hyper::client::Client`
src/main.rs:32:23: 32:52 note:    found type `&hyper::Client`
```

**Comment by paomian** [comment]
It's seem to be the version of hyper.i change the hyper version in my project from 0.9 to 0.8,can resolve this problem.

**Comment by cybergeek94** [comment]
Yes, we can't upgrade to Hyper 0.9 yet, namely because Nickel is still on 0.8. Please use `hyper = "0.8"` in your projects for now, or, for future reference, whatever version of `hyper` that `multipart` declares.
