### ISSUE TITLE
multipart content type ignored, probably due to boundary parameter detection problem

### ISSUE THREAD

**Issue by nicolas-cherel** [cybergeek94/multipart#6]
I tried to investigate why my multipart request was not detected. Step by step, I finally found what would might be a problem, and it seems to be in the mime parameters handling here https://github.com/cybergeek94/multipart/blob/4ceeb41cb4a3f015ccb8f7aeb74b124e96313764/src/server/hyper.rs#L86

I'm not sure what triggered the regression, probably the introduction of [Boundary](https://github.com/hyperium/mime.rs/commit/31d0a83263296979633838873f846145507555cc) as a part of the enum, and when I wrote a small test to figure out what was happening, the Attr::Ext(_) branch of the match was not matched.

###### Test

```rust
mod test {
  use mime::{Mime, TopLevel, SubLevel, Attr, Value};

  #[test]
  fn mime_parse_test() {
    "multipart/form-data; boundary=------------------------674d2efb3fca3c58".parse::<Mime>().and_then(|m| {
      match m {
        Mime(_, _, ref params) => {
          for &(ref known, ref value) in params {
            println!("{:?} {:?}", known, value);
            match *known {
              Attr::Ext(ref name) => println!("named string {:?}", name),
              _ => ()
            };

            match *known {
              Attr::Boundary => println!("known as boundary"),
              _ => ()
            };
          }
        }
      };
      Ok(())
    });
  }
}
```

###### Result

```
running 1 test
Boundary Ext("------------------------674d2efb3fca3c58")
known as boundary
test test::mime_parse_test ... ok
```

By the way, I'm too interested with multipart handling, thanks for refreshing the code and crates !

**Comment by cybergeek94** [comment]
Closed by #7
